services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/18/docker
    networks:
      - backend_database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  migrate:
    build:
      context: .
      dockerfile: docker/Dockerfile.migrate
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend_database
    depends_on:
      database:
        condition: service_healthy
    restart: "no"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_CLIENT_EMAIL=${GCP_CLIENT_EMAIL}
      - GCP_PRIVATE_KEY=${GCP_PRIVATE_KEY}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - NEXTAUTH_SECRET={NEXTAUTH_SECRET}
    networks:
      - frontend_backend
      - backend_database
    depends_on:
      migrate:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    restart: always
    mem_limit: "256m"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3

  proxy:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    networks:
      - frontend_backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      proxy:
        condition: service_started
    environment:
      - CERT_EMAIL=${CERT_EMAIL}
      - CERT_DOMAIN=${CERT_DOMAIN}
      - CERT_DOMAIN_WWW=${CERT_DOMAIN_WWW}
    entrypoint: >
      sh -c "certbot certonly --non-interactive --agree-tos --email $CERT_EMAIL --webroot --webroot-path=/var/www/certbot -d $CERT_DOMAIN -d $CERT_DOMAIN_WWW"

volumes:
  pg_data:
    name: irfancarsandtours_postgres_db
    driver: local

networks:
  frontend_backend:
    driver: bridge

  backend_database:
    driver: bridge
